print(1 and 0 and 2 and 3)
print(0 or False or 9 or False)
print(None or False)
print(False or None)
print(None and False)
print(False and None)
print(1) or print(2) or print(3)
print(1) and print(2)
print(0 or 1 and 2)
print(1 or 0 and 2)
print(False or 0 and 2)
print(True and False or 1)
print(True and True or False)
print(False and 1 or 2)
