print(type(1))
print(type(0))
print(type(1) == type(0))
print(type("hello"))
print(type("hello") == type(""))
print(type(0x67))
print(type(()))
print(type([]))
print(type((1, 2, 3)) == type([1, 2, 3]))
print(type(True))
print(type(False) == type((1, 2, 3)))
print(type(int))
print(type(type))
print(type(int) == type(int))
print(type(float))
print(type(0.0) == type(0))
print(type(0.0))
print(type(object))
print(type(tuple))
print(type(list))
