print('a' == 'b')
print('a' != 'b')
print('a' < 'b')
print('a' <= 'b')
print('a' > 'b')
print('a' >= 'b')

print('b' == 'a')
print('b' != 'a')
print('b' < 'a')
print('b' <= 'a')
print('b' > 'a')
print('b' >= 'a')

print('foo' == 'bar')
print('foo' != 'bar')
print('foo' < 'bar')
print('foo' <= 'bar')
print('foo' > 'bar')
print('foo' >= 'bar')

print('foo' == 'bar')
print('foo' != 'bar')
print('foo' < 'bar')
print('foo' <= 'bar')
print('foo' > 'bar')
print('foo' >= 'bar')

print('Aubergine' == 'Poire')
print('Aubergine' != 'Poire')
print('Aubergine' < 'Poire')
print('Aubergine' <= 'Poire')
print('Aubergine' > 'Poire')
print('Aubergine' >= 'Poire')
